### ISSUE TITLE
Lack of a license

### ISSUE THREAD

**Issue by chatterine** [devinacker/xkas-plus#5]
This software doesn't have a license as of May 22nd 2024. This is bad because I want to be able to redistribute and remix this program's source code without getting into legal trouble, and for unlicensed programs the copyright laws are in effect. I hope that the author can fix this and give it a license (preferrably the GPL v3 or later).

**Comment by devinacker** [comment]
xkas-plus is explicitly in the public domain (i.e. copyright-free), as mentioned at the top of the readme. The original project that this is based on was also released into the public domain, and me applying any other kind of license to it would effectively amount to claiming copyright ownership over code that I didn't write, which I'm obviously not going to do.

**Comment by chatterine** [comment]
hmmm that makes sense. if it's public domain i presume it'd be OK if i redistributed it, yeah?
